version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test-2.7
      - test-3.4
      - test-3.5
      - test-3.6

defaults: &defaults
  working_directory: ~/code
  steps:
  - checkout
  - run:
      name: Install dependencies
      command: pipenv install -r requirements.txt pytest
  - run:
      name: Test
      command: pipenv run pytest

jobs:
  test-2.7:
    <<: *defaults
    docker:
    - image: circleci/python:2.7
    - image: mongo:3.0.7
  test-3.4:
    <<: *defaults
    docker:
    - image: circleci/python:3.4
  test-3.5:
    <<: *defaults
    docker:
    - image: circleci/python:3.5
  test-3.6:
    <<: *defaults
    docker:
    - image: circleci/python:3.6
